### ISSUE TITLE
一些bug...

### ISSUE THREAD

**Issue by flydream3618** [shmilylbelva/laykefu#5]
伪静态规则与代码中要求不一致：

自带伪静态规则：RewriteRule ^(.*)$ index.php?/$1 [QSA,PT,L]
代码中实际要求：RewriteRule ^(.*)$ index.php?s=$1 [QSA,PT,L]

socket地址被写死了，PHP文件中的配置是无效的

**Comment by flydream3618** [comment]
后台管理账号密码缺失，需要自己生成密码哈希，然后手动进数据库替换

**Comment by shmilylbelva** [comment]
> 伪静态规则与代码中要求不一致：
> 
> 自带伪静态规则：RewriteRule ^(._)$ index.php?/$1 [QSA,PT,L] 代码中实际要求：RewriteRule ^(._)$ index.php?s=$1 [QSA,PT,L]
> 
> socket地址被写死了，PHP文件中的配置是无效的

推荐使用nginx，没考虑apache配置
前端socket地址需要自己配置，没有读取配置文件是考虑客户端和服务端不在统一域名上，这里客户端看做单独的服务使用，和后台无关。socket地址也可能是别的ws地址，admin密码未开放是考虑演示地址的后台安全性
