### ISSUE TITLE
我想体验怎么搞

### ISSUE THREAD

**Issue by a6965921** [shmilylbelva/laykefu#6]
用户端的客服聊天弹窗在哪里打开
客服系统后台又在哪里

**Comment by shmilylbelva** [comment]
php环境，运行起来后，默认首页就是用户端窗口页面，客服后台为站点/serice   前台客服：客服小美 密码：123456,演示站：https://www.laykefu.com/

**Comment by shmilylbelva** [comment]
php环境，运行起来后，默认首页就是用户端窗口页面，客服后台为站点/serice   前台客服：客服小美 密码：123456,演示站：https://www.laykefu.com/
